// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
 
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5x35jb0F181VAd6qF5AcMk5zF2K43TI0',
    appId: '1:1093970370081:web:e50383f2733d2ff3f70d60',
    messagingSenderId: '1093970370081',
    projectId: 'meetings-6154a',
    authDomain: 'meetings-6154a.firebaseapp.com',
    storageBucket: 'meetings-6154a.appspot.com',
    measurementId: 'G-1R3HERJZ7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn6tjZ7z_4iaFl4QCtEVpdlm3mZ6w5dz4',
    appId: '1:1093970370081:android:91a1cfe1c3377b57f70d60',
    messagingSenderId: '1093970370081',
    projectId: 'meetings-6154a',
    storageBucket: 'meetings-6154a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5x35jb0F181VAd6qF5AcMk5zF2K43TI0',
    appId: '1:1093970370081:web:4a754bfe4f0d7440f70d60',
    messagingSenderId: '1093970370081',
    projectId: 'meetings-6154a',
    authDomain: 'meetings-6154a.firebaseapp.com',
    storageBucket: 'meetings-6154a.appspot.com',
    measurementId: 'G-DQMNETPZHL',
  );

}